[package]
name = "dev"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.6"
memmap2 = "0.9.4"  # Add this line for memory-mapped files